### ISSUE TITLE
ArrayIndexOutOfBoundException for gradle dependencies

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/LibCompPlugin#30]
This wasn't happening before but today when trying libcomp in a gradle file, I got an exception in this line

```
selectedTerm = valuesInQuotes[0];
```

as follows:

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at smr.cs.ualberta.libcomp.action.ReplacementAction.detectDependancy(ReplacementAction.java:163)
	at smr.cs.ualberta.libcomp.action.ReplacementAction.detectAllOpenEditors(ReplacementAction.java:132)
	at smr.cs.ualberta.libcomp.action.ReplacementAction.update(ReplacementAction.java:218)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:177)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:453)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$null$1(ActionUpdater.java:93)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:133)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$2(ActionUpdater.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:435)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:296)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$19(ActionUpdater.java:275)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1712)
```

**Comment by snadi** [comment]
I need to provide more specific replication instructions

**Comment by relhajj** [comment]
Closing issue because could not replicate this error.
